language: rust
matrix:
  include:
    - name: 1.31.0, core only (Linux)
      rust: 1.31.0
      os: linux
      env: FEATURES="--features std"
    - name: 1.31.0 (Linux)
      rust: 1.31.0
      os: linux
      env: FEATURES="--features std"
    - name: Stable (Linux)
      rust: stable
      os: linux
      env: FEATURES="--features std"
    - name: Stable (macOS)
      rust: stable
      os: osx
      env: FEATURES="--features std"
    - name: Stable (Windows)
      rust: stable
      os: windows
      env: FEATURES="--features std"
    - name: Beta (Linux)
      rust: beta
      os: linux
      env: FEATURES="--features std"
    - name: Nightly (Linux)
      rust: nightly
      os: linux
      env: FEATURES="--features std"
branches:
  only:
    - staging # bors r+
    - trying # bors try
